// Action types
export const GET_TODOS = 'GET_TODOS'
export const GET_TODOS_SUCCEEDED = 'GET_TODOS_SUCCEEDED'
export const GET_TODOS_FAILED = 'GET_TODOS_FAILED'

export const DELETE_TODO = 'DELETE_TODO'
export const DELETE_SUCCEEDED = 'DELETE_SUCCEEDED'
export const DELETE_FAILED = 'DELETE_FAILED'

export const TOGGLE_TODO = 'TOGGLE_TODO'
export const TOGGLE_SUCCEEDED = 'TOGGLE_SUCCEEDED'
export const TOGGLE_FAILED = 'TOGGLE_FAILED'

export const ADD_TODO = 'ADD_TODO'
export const ADD_TODO_SUCCEEDED = 'ADD_TODO_SUCCEEDED'
export const ADD_TODO_FAILED = 'ADD_TODO_FAILED'